CREATE DATABASE PetShop;
GO

USE PetShop;
GO

CREATE TABLE Clinicas(
IdClinicas INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(100) NOT NULL,
Endereco VARCHAR (400) NOT NULL
);

CREATE TABLE Donos (
IdDonos INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(100) NOT NULL
);

CREATE TABLE TipoDePet (
IdTipoDePet INT PRIMARY KEY IDENTITY NOT NULL,
Descricao VARCHAR(100) NOT NULL
);

CREATE TABLE Veterinario(
IdVet INT PRIMARY KEY IDENTITY NOT NULL,
CRMV VARCHAR(50) NOT NULL,
Nome VARCHAR(100) NOT NULL,

IdClinicas INT FOREIGN KEY REFERENCES Clinicas(IdClinicas)
);

CREATE TABLE Raca(
IdRaca INT PRIMARY KEY IDENTITY NOT NULL,
Descricao VARCHAR(500) NOT NULL,


IdTipoDePet INT FOREIGN KEY REFERENCES TipoDePet(IdTipoDePet)
);

CREATE TABLE Pet(
IdPet INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(100) NOT NULL,
DataNascimento DATETIME NOT NULL,

IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca),
IdDonos INT FOREIGN KEY REFERENCES Donos(IdDonos)
);

CREATE TABLE Atendimento(
IdAtendimento INT PRIMARY KEY IDENTITY NOT NULL,
Descricao VARCHAR(500) NOT NULL,
DataAtendimento DATETIME NOT NULL,

IdPet INT FOREIGN KEY REFERENCES Pet(IdPet),
IdVet INT FOREIGN KEY REFERENCES Veterinario(IdVet)
);